version: "2"
services: 
  web:
    build: .
    image: qpair/flaskapp:1.0.0
    ports:
       - "80:5000"
       - "8000:8000"
    mem_limit: 800m
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
